
package ph.belltel.srvc.updatesubscriptionstatus;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-01-09T07:10:40.802+05:30
 * Generated source version: 2.7.1
 * 
 */
 
public class UpdateSubscriptionStatus_UpdateSubscriptionStatusSOAP_Server{

    protected UpdateSubscriptionStatus_UpdateSubscriptionStatusSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new UpdateSubscriptionStatusImpl();
        String address = "http://01hw321300.India.TCS.com:7003/UpdateSubscriptionStatus_SB/ProxyServices/UpdateSubscriptionStatusReqSrvc";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new UpdateSubscriptionStatus_UpdateSubscriptionStatusSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
