
package ph.belltel.srvc.updatesubscriptionstatus;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-01-09T07:10:40.755+05:30
 * Generated source version: 2.7.1
 * 
 */
public final class UpdateSubscriptionStatus_UpdateSubscriptionStatusSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.belltel.ph/Srvc/UpdateSubscriptionStatus/", "UpdateSubscriptionStatus");

    private UpdateSubscriptionStatus_UpdateSubscriptionStatusSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UpdateSubscriptionStatus_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UpdateSubscriptionStatus_Service ss = new UpdateSubscriptionStatus_Service(wsdlURL, SERVICE_NAME);
        UpdateSubscriptionStatus port = ss.getUpdateSubscriptionStatusSOAP();  
        
        {
        System.out.println("Invoking updateSubscription...");
        ph.belltel.ebm.updatesubscriptionstatusrequest.UpdateSubscriptionStatusRequest _updateSubscription_payload = new ph.belltel.ebm.updatesubscriptionstatusrequest.UpdateSubscriptionStatusRequest();
        _updateSubscription_payload.setDealerId("kiran");
        _updateSubscription_payload.setMSISDN("9444735665");
        _updateSubscription_payload.setSubscriptionAction("Add");
        _updateSubscription_payload.setTransactionId("kiran");
        ph.belltel.ebm.updatesubscriptionstatusresponse.UpdateSubscriptionStatusResponse _updateSubscription__return = port.updateSubscription(_updateSubscription_payload);
        System.out.println("updateSubscription.result=" + _updateSubscription__return);
        System.out.println("ResultCode is " + _updateSubscription__return.getResultCode());
        System.out.println("ResultDescription is " + _updateSubscription__return.getResultDescription());

        }

        System.exit(0);
    }

}
