package ph.belltel.srvc.updatesubscriptionstatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-01-09T07:10:40.794+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://www.belltel.ph/Srvc/UpdateSubscriptionStatus/", name = "UpdateSubscriptionStatus")
@XmlSeeAlso({ph.belltel.ebm.updatesubscriptionstatusrequest.ObjectFactory.class, ph.belltel.ebm.updatesubscriptionstatusresponse.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateSubscriptionStatus {

    @WebResult(name = "UpdateSubscriptionStatusResponse", targetNamespace = "http://www.belltel.ph/ebm/UpdateSubscriptionStatusResponse", partName = "payload")
    @WebMethod(action = "http://www.belltel.ph/Srvc/UpdateSubscriptionStatus/")
    public ph.belltel.ebm.updatesubscriptionstatusresponse.UpdateSubscriptionStatusResponse updateSubscription(
        @WebParam(partName = "payload", name = "UpdateSubscriptionStatusRequest", targetNamespace = "http://www.belltel.ph/ebm/UpdateSubscriptionStatusRequest")
        ph.belltel.ebm.updatesubscriptionstatusrequest.UpdateSubscriptionStatusRequest payload
    );
}
