
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ph.belltel.srvc.updatesubscriptionstatus;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-01-09T07:10:40.782+05:30
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "UpdateSubscriptionStatus",
                      portName = "UpdateSubscriptionStatusSOAP",
                      targetNamespace = "http://www.belltel.ph/Srvc/UpdateSubscriptionStatus/",
                      wsdlLocation = "file:/C:/Users/kiran/Desktop/belltell/updatesubscription/updatesubscription/UpdateSubscriptionStatus.wsdl",
                      endpointInterface = "ph.belltel.srvc.updatesubscriptionstatus.UpdateSubscriptionStatus")
                      
public class UpdateSubscriptionStatusImpl implements UpdateSubscriptionStatus {

    private static final Logger LOG = Logger.getLogger(UpdateSubscriptionStatusImpl.class.getName());

    /* (non-Javadoc)
     * @see ph.belltel.srvc.updatesubscriptionstatus.UpdateSubscriptionStatus#updateSubscription(ph.belltel.ebm.updatesubscriptionstatusrequest.UpdateSubscriptionStatusRequest  payload )*
     */
    public ph.belltel.ebm.updatesubscriptionstatusresponse.UpdateSubscriptionStatusResponse updateSubscription(ph.belltel.ebm.updatesubscriptionstatusrequest.UpdateSubscriptionStatusRequest payload) { 
        LOG.info("Executing operation updateSubscription");
        System.out.println(payload);
        try {
            ph.belltel.ebm.updatesubscriptionstatusresponse.UpdateSubscriptionStatusResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
