package ph.belltel.srvc.updatesubscriptionstatus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2013-01-09T07:10:40.805+05:30
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "UpdateSubscriptionStatus", 
                  wsdlLocation = "file:/C:/Users/kiran/Desktop/belltell/updatesubscription/updatesubscription/UpdateSubscriptionStatus.wsdl",
                  targetNamespace = "http://www.belltel.ph/Srvc/UpdateSubscriptionStatus/") 
public class UpdateSubscriptionStatus_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.belltel.ph/Srvc/UpdateSubscriptionStatus/", "UpdateSubscriptionStatus");
    public final static QName UpdateSubscriptionStatusSOAP = new QName("http://www.belltel.ph/Srvc/UpdateSubscriptionStatus/", "UpdateSubscriptionStatusSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/kiran/Desktop/belltell/updatesubscription/updatesubscription/UpdateSubscriptionStatus.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UpdateSubscriptionStatus_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/kiran/Desktop/belltell/updatesubscription/updatesubscription/UpdateSubscriptionStatus.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UpdateSubscriptionStatus_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UpdateSubscriptionStatus_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateSubscriptionStatus_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UpdateSubscriptionStatus_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UpdateSubscriptionStatus_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UpdateSubscriptionStatus_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UpdateSubscriptionStatus
     */
    @WebEndpoint(name = "UpdateSubscriptionStatusSOAP")
    public UpdateSubscriptionStatus getUpdateSubscriptionStatusSOAP() {
        return super.getPort(UpdateSubscriptionStatusSOAP, UpdateSubscriptionStatus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateSubscriptionStatus
     */
    @WebEndpoint(name = "UpdateSubscriptionStatusSOAP")
    public UpdateSubscriptionStatus getUpdateSubscriptionStatusSOAP(WebServiceFeature... features) {
        return super.getPort(UpdateSubscriptionStatusSOAP, UpdateSubscriptionStatus.class, features);
    }

}
